-- =============================================================
-- PedidosPro — Schema completo (MySQL 8 / MariaDB 10.4+, utf8mb4)
-- Nomenclatura padrão Sankhya (TGF*/TSI*, CODEMP). Sem prefixo AD_ em tabela/campo padrão.
-- Reproduz o banco do zero. Depois rode: php artisan db:seed --class=DemoSeeder
-- =============================================================
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS TGFEMP (
  CODEMP INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  RAZAOSOCIAL VARCHAR(120) NOT NULL,
  NOMEFANTASIA VARCHAR(120) NOT NULL,
  CGC VARCHAR(18) NULL,
  RAMO VARCHAR(20) NOT NULL DEFAULT 'VAREJO',
  COR VARCHAR(7) NULL,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSIUSU (
  CODUSU INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOMEUSU VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL,
  SENHA VARCHAR(255) NOT NULL,
  PERFIL VARCHAR(15) NOT NULL DEFAULT 'VENDEDOR',
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  DHULTLOGIN DATETIME NULL,
  DHCRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_TSIUSU_EMAIL (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSIUSUEMP (
  CODUSU INT UNSIGNED NOT NULL,
  CODEMP INT UNSIGNED NOT NULL,
  PRIMARY KEY (CODUSU, CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSIPAR (
  CHAVE VARCHAR(50) NOT NULL,
  CODEMP INT UNSIGNED NOT NULL DEFAULT 0,
  TEXTO TEXT NULL,
  TIPO VARCHAR(10) NOT NULL DEFAULT 'TEXTO',
  DESCRICAO VARCHAR(200) NULL,
  EDITAVEL CHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (CHAVE, CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFPAR (
  CODPARC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  NOMEPARC VARCHAR(120) NOT NULL,
  TIPPESSOA CHAR(1) NOT NULL DEFAULT 'F',
  CGC_CPF VARCHAR(18) NULL,
  TELEFONE VARCHAR(20) NULL,
  EMAIL VARCHAR(150) NULL,
  CIDADE VARCHAR(80) NULL,
  CLIENTE CHAR(1) NOT NULL DEFAULT 'S',
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CEP VARCHAR(9) NULL,
  ENDERECO VARCHAR(120) NULL,
  NUMERO VARCHAR(10) NULL,
  COMPLEMENTO VARCHAR(60) NULL,
  BAIRRO VARCHAR(60) NULL,
  UF CHAR(2) NULL,
  FANTASIA VARCHAR(120) NULL,
  INSCEST VARCHAR(20) NULL,
  INDIE VARCHAR(20) NULL,
  INSCMUN VARCHAR(20) NULL,
  CODMUN VARCHAR(10) NULL,
  PAIS VARCHAR(40) NULL DEFAULT 'Brasil',
  VLRTOTCOMPRAS DECIMAL(15,2) NOT NULL DEFAULT 0,
  KEY IX_TGFPAR_EMP (CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFGRU (
  CODGRUPOPROD INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRGRUPOPROD VARCHAR(80) NOT NULL,
  COR VARCHAR(7) NULL,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  KEY IX_TGFGRU_EMP (CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFVOL (
  CODVOL VARCHAR(6) NOT NULL,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRVOL VARCHAR(60) NOT NULL,
  PRIMARY KEY (CODVOL, CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFPRO (
  CODPROD INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NULL,
  DESCRPROD VARCHAR(120) NOT NULL,
  REFERENCIA VARCHAR(40) NULL,
  CODGRUPOPROD INT UNSIGNED NULL,
  CODVOL VARCHAR(6) NULL,
  VLRVENDA DECIMAL(15,2) NOT NULL DEFAULT 0,
  CUSTOMEDIO DECIMAL(15,2) NOT NULL DEFAULT 0,
  ESTOQUE DECIMAL(15,3) NOT NULL DEFAULT 0,
  ESTMIN DECIMAL(15,3) NOT NULL DEFAULT 0,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY IX_TGFPRO_EMP (CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFPRECO (
  CODPROD INT UNSIGNED NOT NULL,
  SEQUENCIA INT UNSIGNED NOT NULL,
  QTDMIN DECIMAL(15,3) NOT NULL,
  VLRUNIT DECIMAL(15,2) NOT NULL,
  DESCRICAO VARCHAR(60) NULL,
  PRIMARY KEY (CODPROD, SEQUENCIA),
  CONSTRAINT FK_TGFPRECO_PRO FOREIGN KEY (CODPROD) REFERENCES TGFPRO(CODPROD) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFEST (
  CODPROD INT UNSIGNED NOT NULL,
  CODEMP INT UNSIGNED NOT NULL,
  ESTOQUE DECIMAL(15,3) NOT NULL DEFAULT 0,
  RESERVADO DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (CODPROD, CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFTPV (
  CODTIPVENDA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRTIPVENDA VARCHAR(60) NOT NULL,
  TIPO VARCHAR(12) NOT NULL DEFAULT 'DINHEIRO',
  TAXA DECIMAL(6,3) NOT NULL DEFAULT 0,
  PRAZO INT NOT NULL DEFAULT 0,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  KEY IX_TGFTPV_EMP (CODEMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFCAB (
  NUNOTA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NUMNOTA INT UNSIGNED NULL,
  CODEMP INT UNSIGNED NOT NULL,
  CODPARC INT UNSIGNED NULL,
  CODTIPVENDA INT UNSIGNED NULL,
  STATUS VARCHAR(12) NOT NULL DEFAULT 'ABERTO',
  DTNEG DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VLRSUBTOT DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRDESC DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRTOT DECIMAL(15,2) NOT NULL DEFAULT 0,
  CODUSU INT UNSIGNED NULL,
  KEY IX_TGFCAB_EMP (CODEMP, STATUS),
  CONSTRAINT CK_TGFCAB_STATUS CHECK (STATUS IN ('RASCUNHO','ORCAMENTO','ABERTO','SEPARANDO','CONCLUIDO','CANCELADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFITE (
  NUNOTA INT UNSIGNED NOT NULL,
  SEQUENCIA INT UNSIGNED NOT NULL,
  CODPROD INT UNSIGNED NOT NULL,
  QTDNEG DECIMAL(15,3) NOT NULL DEFAULT 1,
  VLRUNIT DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRTOT DECIMAL(15,2) NOT NULL DEFAULT 0,
  DESCRSABOR VARCHAR(80) NULL,
  PRIMARY KEY (NUNOTA, SEQUENCIA),
  CONSTRAINT FK_TGFITE_CAB FOREIGN KEY (NUNOTA) REFERENCES TGFCAB(NUNOTA) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Grade de sabores por produto. Quando um produto tem sabores cadastrados,
-- o pedido/PDV pede a seleção do sabor ao adicionar o item.
CREATE TABLE IF NOT EXISTS TGFPROSAB (
  CODPROD INT UNSIGNED NOT NULL,
  SEQUENCIA INT UNSIGNED NOT NULL,
  DESCRSABOR VARCHAR(80) NOT NULL,
  PRIMARY KEY (CODPROD, SEQUENCIA),
  CONSTRAINT FK_TGFPROSAB_PRO FOREIGN KEY (CODPROD) REFERENCES TGFPRO(CODPROD) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFPAG (
  NUNOTA INT UNSIGNED NOT NULL,
  SEQUENCIA INT UNSIGNED NOT NULL,
  CODTIPVENDA INT UNSIGNED NULL,
  VALOR DECIMAL(15,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (NUNOTA, SEQUENCIA),
  CONSTRAINT FK_TGFPAG_CAB FOREIGN KEY (NUNOTA) REFERENCES TGFCAB(NUNOTA) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSIAUD (
  IDLOG BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DHLOG DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CODEMP INT UNSIGNED NULL,
  CODUSU INT UNSIGNED NULL,
  ENTIDADE VARCHAR(30) NOT NULL,
  CHAVEREG VARCHAR(100) NULL,
  ACAO VARCHAR(20) NOT NULL,
  ORIGEM VARCHAR(20) NOT NULL DEFAULT 'WEB',
  CANAL VARCHAR(60) NULL,
  REQUESTID VARCHAR(40) NULL,
  IPORIGEM VARCHAR(45) NULL,
  DADOSANTES JSON NULL,
  DADOSDEPOIS JSON NULL,
  OBSERVACAO VARCHAR(255) NULL,
  KEY IX_LOGAUD_ENT (CODEMP, ENTIDADE, CHAVEREG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSICAIXA (
  CODCAIXA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  OPERADOR VARCHAR(100) NOT NULL,
  STATUS VARCHAR(10) NOT NULL DEFAULT 'ABERTO',
  DTABERTURA DATETIME NOT NULL,
  VLRABERTURA DECIMAL(15,2) NOT NULL DEFAULT 0,
  DTFECHAMENTO DATETIME NULL,
  VLRCONTADO DECIMAL(15,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSICAIXAMOV (
  CODMOV INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODCAIXA INT UNSIGNED NOT NULL,
  TIPO VARCHAR(12) NOT NULL,
  FORMAPGTO VARCHAR(20) NULL,
  FORMANOME VARCHAR(60) NULL,
  VALOR DECIMAL(15,2) NOT NULL DEFAULT 0,
  DESCRICAO VARCHAR(200) NULL,
  DHMOV DATETIME NOT NULL,
  CONSTRAINT FK_CXMOV FOREIGN KEY (CODCAIXA) REFERENCES TSICAIXA(CODCAIXA) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFNAT (
  CODNAT INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRNAT VARCHAR(80) NOT NULL,
  TIPO VARCHAR(10) NOT NULL DEFAULT 'receita',
  ATIVO CHAR(1) NOT NULL DEFAULT 'S'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSICTA (
  CODCTA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRCTA VARCHAR(80) NOT NULL,
  BANCO VARCHAR(60) NULL,
  AGENCIA VARCHAR(20) NULL,
  CONTA VARCHAR(20) NULL,
  TIPO VARCHAR(12) NOT NULL DEFAULT 'corrente',
  SALDOINI DECIMAL(15,2) NOT NULL DEFAULT 0,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TGFFIN (
  NUFIN INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  TIPO VARCHAR(10) NOT NULL,
  DESCRICAO VARCHAR(200) NOT NULL,
  VLRDESDOB DECIMAL(15,2) NOT NULL DEFAULT 0,
  DTVENC DATE NULL,
  STATUS VARCHAR(12) NOT NULL DEFAULT 'aberto',
  CODNAT INT UNSIGNED NULL,
  CODCTA INT UNSIGNED NULL,
  FORMAPGTO VARCHAR(60) NULL,
  ORIGEM VARCHAR(12) NOT NULL DEFAULT 'manual',
  CODCAIXA INT UNSIGNED NULL,
  DHCRIACAO DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TSIINTEGR (
  CODINTEG INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP INT UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  TOKEN VARCHAR(80) NOT NULL,
  ATIVO CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_INTEG_TOKEN (TOKEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Controle de envio de orçamentos pelo WhatsApp (extensão).
-- Guarda o hash do orçamento já enviado; muda o hash quando o orçamento é
-- alterado, permitindo reenviar só quando muda e nunca repetir o mesmo.
CREATE TABLE IF NOT EXISTS TSIORCWA (
  NUNOTA INT UNSIGNED NOT NULL PRIMARY KEY,
  HASHENVIO VARCHAR(64) NOT NULL,
  DHENVIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_TSIORCWA_CAB FOREIGN KEY (NUNOTA) REFERENCES TGFCAB(NUNOTA) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- Reference/seed data (não-bcrypt). Usuários/empresas/produtos vêm do DemoSeeder.
INSERT IGNORE INTO TSIPAR (CHAVE, CODEMP, TEXTO, TIPO, DESCRICAO, EDITAVEL) VALUES
  ('COMPARTILHA_PRODUTO_FILIAIS', 0, 'S', 'BOOL', 'Compartilha cadastro de produtos entre todas as empresas', 'S');
