-- =============================================================
-- PedidosPro — Schema MySQL 8 (utf8mb4)
-- Nomenclatura padrão Sankhya (TGF*/TSI*, CODEMP). Dialeto MySQL.
-- Prefixo AD_ é RESERVADO para customizações futuras — nenhuma tabela/campo padrão usa AD_.
-- Fonte de verdade do modelo: docs/ARQUITETURA.md
-- =============================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------- Empresas (filiais) ----------
CREATE TABLE TGFEMP (
  CODEMP        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  RAZAOSOCIAL   VARCHAR(120) NOT NULL,
  NOMEFANTASIA  VARCHAR(120) NOT NULL,
  CGC           VARCHAR(18) NULL,               -- CNPJ
  RAMO          VARCHAR(20) NOT NULL DEFAULT 'VAREJO', -- VAREJO|ALIMENTACAO|ATACADO|SERVICOS|OUTRO
  COR           VARCHAR(7) NULL,                -- cor do avatar
  ATIVO         CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_TGFEMP_CGC (CGC)
) ENGINE=InnoDB;

-- ---------- Usuários ----------
CREATE TABLE TSIUSU (
  CODUSU        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOMEUSU       VARCHAR(100) NOT NULL,
  EMAIL         VARCHAR(150) NOT NULL,          -- login
  SENHA         VARCHAR(255) NOT NULL,          -- hash bcrypt
  PERFIL        VARCHAR(15) NOT NULL DEFAULT 'VENDEDOR', -- ADMINISTRADOR|VENDEDOR|CAIXA
  ATIVO         CHAR(1) NOT NULL DEFAULT 'S',
  DHULTLOGIN    DATETIME NULL,
  DHCRIACAO     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_TSIUSU_EMAIL (EMAIL),
  CONSTRAINT CK_TSIUSU_PERFIL CHECK (PERFIL IN ('ADMINISTRADOR','VENDEDOR','CAIXA'))
) ENGINE=InnoDB;

-- ---------- Acesso usuário x empresa (multiempresa) ----------
CREATE TABLE TSIUSUEMP (
  CODUSU  INT UNSIGNED NOT NULL,
  CODEMP  INT UNSIGNED NOT NULL,
  PRIMARY KEY (CODUSU, CODEMP),
  CONSTRAINT FK_USUEMP_USU FOREIGN KEY (CODUSU) REFERENCES TSIUSU(CODUSU) ON DELETE CASCADE,
  CONSTRAINT FK_USUEMP_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------- Parâmetros ----------
CREATE TABLE TSIPAR (
  CHAVE      VARCHAR(50) NOT NULL,
  CODEMP     INT UNSIGNED NOT NULL DEFAULT 0,   -- 0 = global; >0 = específico da empresa
  TEXTO      TEXT NULL,
  TIPO       VARCHAR(10) NOT NULL DEFAULT 'TEXTO', -- TEXTO|NUMERO|BOOL|JSON
  DESCRICAO  VARCHAR(200) NULL,
  EDITAVEL   CHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (CHAVE, CODEMP)
) ENGINE=InnoDB;
-- CODEMP=0 é o sentinela "global" (não referencia TGFEMP; por isso sem FK).
-- Resolução: parâmetro com CODEMP=<empresa> tem precedência sobre o de CODEMP=0.
-- MySQL não aceita NULL em PRIMARY KEY, por isso 0 em vez de NULL.

-- ---------- Parceiros (clientes) ----------
CREATE TABLE TGFPAR (
  CODPARC       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP        INT UNSIGNED NOT NULL,
  NOMEPARC      VARCHAR(120) NOT NULL,          -- nome/razão social
  TIPPESSOA     CHAR(1) NOT NULL DEFAULT 'F',   -- F|J
  CGC_CPF       VARCHAR(18) NULL,
  TELEFONE      VARCHAR(20) NULL,
  EMAIL         VARCHAR(150) NULL,
  CIDADE        VARCHAR(80) NULL,
  CLIENTE       CHAR(1) NOT NULL DEFAULT 'S',
  ATIVO         CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY IX_TGFPAR_EMP (CODEMP),
  CONSTRAINT FK_TGFPAR_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP)
) ENGINE=InnoDB;

-- ---------- Grupos de produto ----------
CREATE TABLE TGFGRU (
  CODGRUPOPROD   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP         INT UNSIGNED NOT NULL,
  DESCRGRUPOPROD VARCHAR(80) NOT NULL,
  COR            VARCHAR(7) NULL,
  ATIVO          CHAR(1) NOT NULL DEFAULT 'S',
  KEY IX_TGFGRU_EMP (CODEMP),
  CONSTRAINT FK_TGFGRU_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP)
) ENGINE=InnoDB;

-- ---------- Unidades (volume) ----------
CREATE TABLE TGFVOL (
  CODVOL     VARCHAR(6) NOT NULL,               -- sigla (UN, KG, CX...)
  CODEMP     INT UNSIGNED NOT NULL,
  DESCRVOL   VARCHAR(60) NOT NULL,
  PRIMARY KEY (CODVOL, CODEMP),
  CONSTRAINT FK_TGFVOL_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP)
) ENGINE=InnoDB;

-- ---------- Produtos (CODEMP NULL = compartilhado, ver COMPARTILHA_PRODUTO_FILIAIS) ----------
CREATE TABLE TGFPRO (
  CODPROD       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP        INT UNSIGNED NULL,              -- NULL = compartilhado entre filiais
  DESCRPROD     VARCHAR(120) NOT NULL,
  REFERENCIA    VARCHAR(40) NULL,               -- SKU
  CODGRUPOPROD  INT UNSIGNED NULL,
  CODVOL        VARCHAR(6) NULL,
  VLRVENDA      DECIMAL(15,2) NOT NULL DEFAULT 0,
  ESTMIN        DECIMAL(15,3) NOT NULL DEFAULT 0, -- estoque mínimo
  ATIVO         CHAR(1) NOT NULL DEFAULT 'S',
  DHCRIACAO     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY IX_TGFPRO_EMP (CODEMP),
  KEY IX_TGFPRO_GRU (CODGRUPOPROD),
  CONSTRAINT FK_TGFPRO_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP),
  CONSTRAINT FK_TGFPRO_GRU FOREIGN KEY (CODGRUPOPROD) REFERENCES TGFGRU(CODGRUPOPROD)
) ENGINE=InnoDB;

-- ---------- Estoque (saldo por empresa, sempre) ----------
CREATE TABLE TGFEST (
  CODPROD    INT UNSIGNED NOT NULL,
  CODEMP     INT UNSIGNED NOT NULL,
  ESTOQUE    DECIMAL(15,3) NOT NULL DEFAULT 0,
  RESERVADO  DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (CODPROD, CODEMP),
  CONSTRAINT FK_TGFEST_PRO FOREIGN KEY (CODPROD) REFERENCES TGFPRO(CODPROD),
  CONSTRAINT FK_TGFEST_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP)
) ENGINE=InnoDB;

-- ---------- Formas de pagamento (tipos de negociação) ----------
CREATE TABLE TGFTPV (
  CODTIPVENDA   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CODEMP        INT UNSIGNED NOT NULL,
  DESCRTIPVENDA VARCHAR(60) NOT NULL,
  TIPO          VARCHAR(12) NOT NULL DEFAULT 'DINHEIRO', -- DINHEIRO|PIX|CARTAO|BOLETO|TRANSFERENCIA
  TAXA          DECIMAL(6,3) NOT NULL DEFAULT 0,   -- taxa %
  PRAZO         INT NOT NULL DEFAULT 0,            -- dias p/ recebimento (D+n)
  ATIVO         CHAR(1) NOT NULL DEFAULT 'S',      -- ativas alimentam o PDV
  KEY IX_TGFTPV_EMP (CODEMP),
  CONSTRAINT FK_TGFTPV_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP)
) ENGINE=InnoDB;

-- ---------- Pedidos: cabeçalho ----------
CREATE TABLE TGFCAB (
  NUNOTA      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NUMNOTA     INT UNSIGNED NULL,                 -- número visível do pedido
  CODEMP      INT UNSIGNED NOT NULL,
  CODPARC     INT UNSIGNED NULL,                 -- NULL = consumidor não identificado
  CODTIPVENDA INT UNSIGNED NULL,                 -- forma de pagamento
  STATUS      VARCHAR(12) NOT NULL DEFAULT 'RASCUNHO', -- RASCUNHO|ABERTO|SEPARANDO|CONCLUIDO|CANCELADO
  DTNEG       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VLRSUBTOT   DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRDESC     DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRTOT      DECIMAL(15,2) NOT NULL DEFAULT 0,
  CODUSU      INT UNSIGNED NULL,                 -- quem lançou
  KEY IX_TGFCAB_EMP (CODEMP, STATUS),
  CONSTRAINT FK_TGFCAB_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP),
  CONSTRAINT FK_TGFCAB_PAR FOREIGN KEY (CODPARC) REFERENCES TGFPAR(CODPARC),
  CONSTRAINT CK_TGFCAB_STATUS CHECK (STATUS IN ('RASCUNHO','ABERTO','SEPARANDO','CONCLUIDO','CANCELADO'))
) ENGINE=InnoDB;

-- ---------- Pedidos: itens ----------
CREATE TABLE TGFITE (
  NUNOTA     INT UNSIGNED NOT NULL,
  SEQUENCIA  INT UNSIGNED NOT NULL,
  CODPROD    INT UNSIGNED NOT NULL,
  QTDNEG     DECIMAL(15,3) NOT NULL DEFAULT 1,
  VLRUNIT    DECIMAL(15,2) NOT NULL DEFAULT 0,
  VLRTOT     DECIMAL(15,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (NUNOTA, SEQUENCIA),
  CONSTRAINT FK_TGFITE_CAB FOREIGN KEY (NUNOTA) REFERENCES TGFCAB(NUNOTA) ON DELETE CASCADE,
  CONSTRAINT FK_TGFITE_PRO FOREIGN KEY (CODPROD) REFERENCES TGFPRO(CODPROD)
) ENGINE=InnoDB;

-- ---------- Auditoria (append-only) ----------
CREATE TABLE TSIAUD (
  IDLOG        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DHLOG        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CODEMP       INT UNSIGNED NULL,
  CODUSU       INT UNSIGNED NULL,
  ENTIDADE     VARCHAR(30) NOT NULL,
  CHAVEREG     VARCHAR(100) NULL,
  ACAO         VARCHAR(20) NOT NULL,             -- INSERT|UPDATE|DELETE|LOGIN|LOGOUT|EXPORT|STATUS
  ORIGEM       VARCHAR(20) NOT NULL DEFAULT 'WEB', -- WEB|PDV|API|INTEGRACAO|IA
  CANAL        VARCHAR(60) NULL,                 -- X-Integration-Key
  REQUESTID    VARCHAR(40) NULL,
  IPORIGEM     VARCHAR(45) NULL,
  DADOSANTES   JSON NULL,
  DADOSDEPOIS  JSON NULL,
  OBSERVACAO   VARCHAR(255) NULL,
  KEY IX_LOGAUD_ENT (CODEMP, ENTIDADE, CHAVEREG),
  KEY IX_LOGAUD_CANAL (CANAL, DHLOG),
  KEY IX_LOGAUD_USU (CODUSU, DHLOG)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================
-- Seed inicial de parâmetros
-- =============================================================
INSERT INTO TSIPAR (CHAVE, CODEMP, TEXTO, TIPO, DESCRICAO, EDITAVEL) VALUES
  ('COMPARTILHA_PRODUTO_FILIAIS', 0, 'S', 'BOOL',
   'Compartilha cadastro de produtos entre todas as empresas', 'S');
-- CODEMP=0 representa o parâmetro global (ver docs/PADRAO-PARAMETROS.md).
